### PR TITLE
Allow closing of partial run

### PR DESCRIPTION
**Pull request by jlozano**
Allows clients to close the partial run and free associated resources. Unfortunately, this comment https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.cc#L2347 seems to indicate that this will not do anything, I am going to dig into this tmrw.

### CODE REVIEW

**Comment by metalogical** [comment]
be careful when vendoring this, since we have manually edited some files in the vendored copy to provide the correct linker directives.

**Comment by jlozano** [comment]
@metalogical yikes! Is there a reason why we do not edit those files in this repo instead?

**Comment by metalogical** [comment]
I think the main reason was that the headers etc live inside `kiteco`, so we need to refer to them here as `../../../...../foo/bar/header.h` or whatever. I tried to move stuff around to fix this, but the Go linker setup is surprisingly brittle, and it wasn't worth the time.

**Comment by jlozano** [comment]
Closing this, we are taking care of this at the application layer by ensuring that we always retrieve all `fetch` ops and thus tensorflow automatically cleans up the session.

**Pull request closed without merging**
